name: Deploy to Oracle Linux Cloud

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Send Alert to Discord that the bot is stopping
              uses: tsickert/discord-webhook@v5.3.0
              with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                raw-data: "json/server-stop.json"

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Oracle Linux Cloud
              run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} "cd ${{ secrets.PROYECT_DIR }} && bash deploy.sh"

            - name: Send Alert to Discord that the bot is starting
              uses: tsickert/discord-webhook@v5.3.0
              with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                raw-data: "json/server-start.json"